import React from 'react';
import Head from 'next/head';

export default function MyHead({ subTitle }: { subTitle?: string }) {
  return (
    <Head>
      <title>tsp-live {subTitle ? `| ${subTitle}` : ''}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
